name: Build & Push Microservices

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - auth
          - profile
          - messenger
          - finance
          - share

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to AWS ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t zongdev-${{ matrix.service }} ./Microservices/${{ matrix.service }}

      - name: Tag & Push Images (ECR + DockerHub)
        run: |
          VERSION="1.0.0"

          # --- DockerHub repo name ---
          HUB_IMAGE="songhieng2k25/zongdev-${{ matrix.service }}:${VERSION}"

          # --- AWS ECR repo name ---
          ECR_IMAGE="${{ steps.ecr.outputs.registry }}/zongdev-${{ matrix.service }}:${VERSION}"

          # Tag
          docker tag zongdev-${{ matrix.service }} $HUB_IMAGE
          docker tag zongdev-${{ matrix.service }} $ECR_IMAGE

          # Push to DockerHub
          docker push $HUB_IMAGE

          # Push to AWS ECR
          docker push $ECR_IMAGE
